<?php

namespace DoctrineMongoDBHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class TimeshareEntitiesServicesHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['time'])) {
            $value = $data['time'];
            $return = (int) $value;
            $this->class->reflFields['time']->setValue($document, $return);
            $hydratedData['time'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['note'])) {
            $value = $data['note'];
            $return = (int) $value;
            $this->class->reflFields['note']->setValue($document, $return);
            $hydratedData['note'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['debiteur'])) {
            $reference = $data['debiteur'];
            if (isset($this->class->fieldMappings['debiteur']['simple']) && $this->class->fieldMappings['debiteur']['simple']) {
                $className = $this->class->fieldMappings['debiteur']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['debiteur'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['debiteur']->setValue($document, $return);
            $hydratedData['debiteur'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['crediteur'])) {
            $reference = $data['crediteur'];
            if (isset($this->class->fieldMappings['crediteur']['simple']) && $this->class->fieldMappings['crediteur']['simple']) {
                $className = $this->class->fieldMappings['crediteur']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['crediteur'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['crediteur']->setValue($document, $return);
            $hydratedData['crediteur'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['annonce'])) {
            $reference = $data['annonce'];
            if (isset($this->class->fieldMappings['annonce']['simple']) && $this->class->fieldMappings['annonce']['simple']) {
                $className = $this->class->fieldMappings['annonce']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['annonce'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['annonce']->setValue($document, $return);
            $hydratedData['annonce'] = $return;
        }
        return $hydratedData;
    }
}