getAll:
  path: /
  defaults: { _controller: 'Timeshare\Controllers\AnnonceController::getAllAction' }
  methods:  [GET]

getOne:
  path: /{id}
  defaults: { _controller: 'Timeshare\Controllers\AnnonceController::getOneAction' }
  methods:  [GET]

deleteOne:
  path: /{id}
  defaults: { _controller: 'Timeshare\Controllers\AnnonceController::deleteOneAction' }
  methods:  [DELETE]

addOne:
  path: /
  defaults: { _controller: 'Timeshare\Controllers\AnnonceController::addOneAction' }
  methods:  [POST]

editOne:
  path: /{id}
  defaults: { _controller: 'Timeshare\Controllers\AnnonceController::editOneAction' }
  methods:  [PUT]
  
sortAction:
  path: /{category}/{lieu}
  defaults: { _controller: 'Timeshare\Controllers\AnnonceController::sortAnnonce' }
  methods:  [GET]  
<<<<<<< HEAD
=======
  
sortByAuthor:
    path: /auteur/{author}
    defaults: { _controller: 'Timeshare\Controllers\AnnonceController::annonceByAuthor' }
    methods:  [GET]
>>>>>>> 122a6780b561b6dff590275ffacbe9b8535bca61
