getAll:
  path: /
  defaults: { _controller: 'Timeshare\Controllers\AnnonceController::getAllAction' }
  methods:  [GET]

getOne:
  path: /{id}
  defaults: { _controller: 'Timeshare\Controllers\AnnonceController::getOneAction' }
  methods:  [GET]

deleteOne:
  path: /{id}
  defaults: { _controller: 'Timeshare\Controllers\AnnonceController::deleteOneAction' }
  methods:  [DELETE]

addOne:
  path: /
  defaults: { _controller: 'Timeshare\Controllers\AnnonceController::addOneAction' }
  methods:  [POST]

editOne:
  path: /{id}
  defaults: { _controller: 'Timeshare\Controllers\AnnonceController::editOneAction' }
  methods:  [PUT]
  
editOne:
  path: /{id}
  defaults: { _controller: 'Timeshare\Controllers\AnnonceController::editOneAction' }
  methods:  [PUT]  