getAll:
  path: /
  defaults: { _controller: 'Todos\Controllers\TodoController::getAllAction' }
  methods:  [GET]

getOne:
  path: /{id}
  defaults: { _controller: 'Todos\Controllers\TodoController::getOneAction' }
  methods:  [GET]

deleteOne:
  path: /{id}
  defaults: { _controller: 'Todos\Controllers\TodoController::deleteOneAction' }
  methods:  [DELETE]

addOne:
  path: /
  defaults: { _controller: 'Todos\Controllers\TodoController::addOneAction' }
  methods:  [POST]

editOne:
  path: /{id}
  defaults: { _controller: 'Todos\Controllers\TodoController::editOneAction' }
  methods:  [PUT]